### ISSUE TITLE
Como usuario adicto al sudoku  quiero que el juego no se quede bloqueado cuando termino una partida para poder jugar otra

### ISSUE THREAD

**Issue by pablofontanilla** [CEU-GITAV-INSW/practica-1-2-grupo-1#46]
Actualmente el juego se queda bloqueado al poner el último número

Criterios de Aceptación

Se muestra una pantalla de éxito y se ofrece comenzar una partida nueva

**Comment by LUCIA0BGM** [comment]
@gsalicruu @GonzaloFrancoGarcia @kzacarias Cuando podáis revisadlo y ya nos ponemos con el game loop y todo eso :)
