### ISSUE TITLE
Como usuario hiper-competitivo, cuando pierda quiero que me lo digan y me ofrezcan empezar de nuevo lo antes posible

### ISSUE THREAD

**Issue by pablofontanilla** [CEU-GITAV-INSW/practica-1-2-grupo-1#47]
El juego no me dice que he ganado cuando me quedo sin tiempo, me dice que he perdido. Además, cuando le digo que quiero jugar otra vez, me devuelve al menú principal. Debería mandarme a Iniciar Partida directamente. Quiero ganar cuanto antes!!!!

Criterio de Aceptación

Cuando se acaba el tiempo, el juego solo me dice que he ganado si todas las casillas están completadas. Cuando me ofrece una partida nueva, no quiero volver al menú principal, quiero volver a jugar inmediatamente

**Comment by LUCIA0BGM** [comment]
Queda arreglado junto al issue #46
